name: Docker Container Builds

on:
  push:
    tags:
      - "adt-v*.*.*"

  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every day at 5:24 UTC - build 'latest' docker containers
    - cron:  '24 5 * * *'

jobs:
  build-and-push:
    runs-on:
      - self-hosted
      - linux
    strategy:
      matrix:
        kind:
          - ephemeral
          - postgres
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into registry
        run: >-
          echo "${{ secrets.GITHUB_TOKEN }}" |
          docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: >
          docker build .
          --file docker/pwpush-${{ matrix.kind }}/Dockerfile
          --tag pwpush-${{ matrix.kind }}

      - name: Push image
        id: push_image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/pwpush-${{ matrix.kind }}
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && \
            VERSION=$(echo $VERSION | sed -e 's/^adt-v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          echo "img_ref=$IMAGE_ID:$VERSION" >> $GITHUB_ENV
          docker tag pwpush-${{ matrix.kind }} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
